---
- name: Create Application on Ravello
  connection: local
  hosts: junos,server
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.create_topology
  pre_tasks:
    - include_vars: user-input.yaml
