---
- hosts: server
  become: true
  # become_user: ubuntu

  # roles:
  # - role: dresden-weekly.network-interfaces
  #   network_manage_devices: no
  #
  #   network_interfaces:
  #   - device: eth1
  #     description: just a description for humans to understand
  #     auto: true
  #     family: inet
  #     method: static
  #     address: "{{ mgmt_ip }}"
  #     network: "{{ mgmt_network }}"
  #     netmask: "{{ mgmt_mask }}"
  #     #gateway: "{{ mgmt_gateway }}"
  tasks:

  - name: Update apt-get cache
    apt: update_cache=yes cache_valid_time=3600

  - name: Install Python PIP
    apt: name=python-pip state=present

  - name: Install dependancy (network-manager)
    apt: name=network-manager state=present

  - name: Install dependancy (dbus)
    apt: name=python-dbus state=present

  - pip: name=python-networkmanager

  - name: Try nmcli add team - cname only & ip4 gw4
    nmcli: type=ethernet cname=eth1 ip4={{eth1_ip}} state=present
  - command: route add -net 100.0.0.0 netmask 255.255.0.0 gw {{ default_gw }}
