
loopback_ip: 1.1.1.12

underlay:
    local:
        asn: 60012
    neighbors:
      - interface: em3
        name: spine1
        asn: 60001
        peer_ip: "{{ p2p.link3.1 }}"
        local_ip: "{{ p2p.link3.2 }}"
      - interface: em4
        name: spine2
        asn: 60002
        peer_ip: "{{ p2p.link4.1 }}"
        local_ip: "{{ p2p.link4.2 }}"

junos_std_l3:
    - name: em5
      units:
      - id: 0
        ip: 100.0.8.1
        mask: 24
